### PR TITLE
port to PyQt6

### PR DESCRIPTION
**Pull request by trel**
I was having trouble building/installing PyQt5 on Apple Silicon.

Turns out, a few things moved in PyQt6.  But this builds, and appears to work as well as before I touched anything.

### CODE REVIEW

**Comment by chStaiger** [comment]
Many thanks @trel. We  will test on linux and Windows!

**Comment by trel** [comment]
I'm happy to rebase or tweak the commit messages...

Where would you like bug reports?   In this repository?

I see there's also a fork with new activity at https://github.com/rijksuniversiteit-groningen/iBridges ...

**Comment by chStaiger** [comment]
At the moment this is still the main repository.

**Comment by trel** [comment]
Gotcha - thanks.

**Comment by trel** [comment]
this is now built on top of #3 (that should be merged first)

**Comment by chStaiger** [comment]
This needs a bit more work. The checkboxes of filesystem trees in "tabUpDownload" are not checkable. But I am thinking about changing that to the row-select mode as in the browser table.

**Comment by chStaiger** [comment]
> I was having trouble building/installing PyQt5 on Apple Silicon.
> 
> Turns out, a few things moved in PyQt6. But this builds, and appears to work as well as before I touched anything.

I could only install PyQt5 with homebrew and the respective python compiler from homebrew. But now I have both versions.

**Comment by trel** [comment]
> The checkboxes of filesystem trees in "tabUpDownload" are not checkable.

Yes, I could not figure out the wiring for those.   Thanks.

Does the up/download tab become redundant if the main browser tree learns to drag/drop?   Both single files as well as directories/collections?    I've not worked with Qt before, so I'm not sure if that's a silly/hard question.

**Comment by trel** [comment]
naive clicking around suggests... it's approachable... 
  https://www.riverbankcomputing.com/static/Docs/PyQt6/api/qtgui/qdrag.html

**Comment by chStaiger** [comment]
> > The checkboxes of filesystem trees in "tabUpDownload" are not checkable.
> 
> Yes, I could not figure out the wiring for those. Thanks.
> 
> Does the up/download tab become redundant if the main browser tree learns to drag/drop? Both single files as well as directories/collections? I've not worked with Qt before, so I'm not sure if that's a silly/hard question.

The Up and Download tab was actually meant as a prototype for data synchronisation between a local FS and iRODS. When you have large data and you upload them through the main browser you will not be able to inspect and edit other (meta)data in the meantime. So we created this separate view for large data transfers which starts also a separate QThread for the data transfers. By this the data transfer is taking part in the background while a user can execute actions through all other tabs in the GUI.

**Comment by chStaiger** [comment]
I moved your code from this pull request into the separate branch *pyqt6* for further development and testing.

**Pull request closed without merging**
