### PR TITLE
Create iBridges-alpha-0.0.1

### PR DESCRIPTION
**Pull request by chStaiger**
Last checks before new minor version
- [x] Browser: Upload, Download, Create collection, Metadata tab, ACL tab, Delete tab
- [x] Data Transfers: Upload and download of test data folder, test data file
- [x] ELabJournal tab
- [x] Amberscript tab
- [x] Bundle and unbundle data
- [x] Create access tokens tab
- [x] CLI: upload
- [x] CLI: download

- removed ContextContainer from GUI classes, ContextContainer is labeled as deprecated
- Adjusted documentation: adding bundeling of data, referring supported iRODS versions
- I added a bug report and feature request template

Can you please do a last sanity check before I create the new release?

### CODE REVIEW

**Comment by wurDevTim** [comment]
Small point I noticed during this testing round, if you download a file which already exists in your downloads, or other, folder iBridges says it downloaded it. While it skipped the file...

**Comment by wurDevTim** [comment]
A second small point is that there is a 'save config' option in the menubar which does not provide any feedback. That feels a bit strange.

Lastly its a bit confusing that some log messages: 'Only tabBrowser, tabUpDownload, tabDataBundle, tabCreateTicket, tabELNData, tabAmberWorkflow, tabInfo, tabExample tabs supported'  appears in the DataTransfertabs when you enter an unknown tab. 

We still have to redo the entire Data Transfer tab. For now, be advised that it currently does not release the UI after a transfer caused an error. Or when 'cancel' is pressed while the background thread is still running. 

I think these minor bugs are acceptable in an alpha version, besides the rest of the code & UI look a lot better. We have really done a lot over the last months.

**Review by wurDevTim — APPROVED** [review]

**Comment by chStaiger** [comment]
> Small point I noticed during this testing round, if you download a file which already exists in your downloads, or other, folder iBridges says it downloaded it. While it skipped the file...

I will delete the option. It will become obsolete anyways with the config editor feature, which is planned for the next development cycle.

**Comment by chStaiger** [comment]
> A second small point is that there is a 'save config' option in the menubar which does not provide any feedback. That feels a bit strange.
> 
> Lastly its a bit confusing that some log messages: 'Only tabBrowser, tabUpDownload, tabDataBundle, tabCreateTicket, tabELNData, tabAmberWorkflow, tabInfo, tabExample tabs supported' appears in the DataTransfertabs when you enter an unknown tab.
> 
> We still have to redo the entire Data Transfer tab. For now, be advised that it currently does not release the UI after a transfer caused an error. Or when 'cancel' is pressed while the background thread is still running.
> 
> I think these minor bugs are acceptable in an alpha version, besides the rest of the code & UI look a lot better. We have really done a lot over the last months.

I created issues for your points and the crashes in the Data Transfers Tab were already present
https://github.com/chStaiger/iBridges-Gui/issues/25

Will be picked up!

**Comment by jpmcfarland** [comment]
> > A second small point is that there is a 'save config' option in the menubar which does not provide any feedback. That feels a bit strange.
> 
> > 
> 
> > Lastly its a bit confusing that some log messages: 'Only tabBrowser, tabUpDownload, tabDataBundle, tabCreateTicket, tabELNData, tabAmberWorkflow, tabInfo, tabExample tabs supported' appears in the DataTransfertabs when you enter an unknown tab.
> 
> > 
> 
> > We still have to redo the entire Data Transfer tab. For now, be advised that it currently does not release the UI after a transfer caused an error. Or when 'cancel' is pressed while the background thread is still running.
> 
> > 
> 
> > I think these minor bugs are acceptable in an alpha version, besides the rest of the code & UI look a lot better. We have really done a lot over the last months.
> 
> 
> 
> I created issues for your points and the crashes in the Data Transfers Tab were already present
> 
> https://github.com/chStaiger/iBridges-Gui/issues/25
> 
> 
> 
> Will be picked up!

I believe I already have code that addresses some of these issues.  I will survey it and add comments to the relevant issues.

**Pull request merged**
